import numpy as np
import viktor as vkt
from src.Dsettl_results import extract_iteration_results_dset


def create_Dset_geometry(df_bh, groundlevel, material_table):
        """
        Create geometry lists for geological layers including colors and names
        """
        material = []
        depth_top = []
        depth_base = []
        color = []
        name = []
        thickness = []
        
        # Define material colors and names inside the function
        material_colors = {}
        for row in material_table:
             material_name = row['col_1']
             material_color = row['col_4']
             material_colors[material_name] = material_color
        
        # Creating lists
        for index, row in df_bh.iterrows():
            mat = row['Description']
            d_top = np.round(-row['Depth Top'] + groundlevel, 2)
            d_base = np.round(-row['Depth Base'] + groundlevel, 2)
            thick = np.round(d_top - d_base, 2)  # Fixed parenthesis
            
            material.append(mat)
            depth_top.append(d_top)
            depth_base.append(d_base)
            thickness.append(thick)
            color.append(material_colors.get(mat, 'white'))
            name.append(mat)
        
        return material, depth_top, depth_base, color, name, thickness



def create_Dset_model(model_type, consol_type, location, df_loc, df_bh, material_table, coord_system, load):
    if df_loc is not None:
        # Get location data
        selected_location = df_loc[df_loc['Location ID'] == location]

    if (df_bh is not None and location is not None):
        # Get the filtered borehole data
        filtered_df_bh = df_bh[df_bh['Location ID'] == location]
        groundlevel = selected_location['Ground Level'].iloc[0]

    if not filtered_df_bh.empty:
            # Use create_geometry function to get all lists
            materials, depth_tops, depth_bases, colors, names, thicknesses = create_Dset_geometry(filtered_df_bh, groundlevel)

    # Create model
    model_dset = vkt.dsettlement.Model1D(model_type, consol_type)

    # Create material(s) - Fixed to handle table data properly
    for row in material_table:
        model_dset.create_material(
            row['col_1'],  # Material name
            row['col_2'],  # Volume weight unsat
            row['col_3'],  # Volume weight sat
            vkt.Color(row['col_4']),  # Color (now already a Color object from ColorField)
            rr=row['col_5'],  # RR
            cr=row['col_6'],  # CR
            ca=row['col_7']   # Ca
        )

    # Create geometry - layers
    # Fixed: Use min() to find minimum value
    bottom_level = min(depth_bases) - 10  # 10m below deepest layer

    layer_tuples = []
    for i in range(len(names)):
        layer_tuples.append((depth_tops[i], names[i]))

    print(layer_tuples)

    # Update geometry in model
    # Bottom of the model is 2m below the lowest layer
    model_dset.update_geometry(np.min(depth_bases)-2, layer_tuples)

    # Create load(s)
    model_dset.create_uniform_load("Uniform load", time = 0, unit_weight = load, height=1.0, y_application=groundlevel)

    # Generate the input file for the model as if it was generated by D-Settlement.
    # Metadata can be used (not required) to update data such as created_by, titles, etc.
    metadata = vkt.dsettlement.Metadata(title_1='Settlement Model', created_by='Maureen Danique Klomp')
    input_file = model_dset.generate_input_file(metadata)

    # Run the analysis with the generated input file (requires worker).
    analysis = vkt.dsettlement.DSettlementAnalysis(input_file)
    analysis.execute(300)

    # Obtain the result file.
    sld_file = analysis.get_sld_file()

    # Save to a local file (if running locally)
    # with open("dsettl_results.fod", "wb") as f:
    #     f.write(sld_file.getvalue())

    # Read the raw content
    sld_bytes = sld_file.getvalue()
    sld_string = sld_bytes.decode('utf-8')

    # TODO Create own parser for settlement results
    # result = extract_iteration_results_dset(sld_string)

    return sld_string
    # return result